### ISSUE TITLE
Conduit_Landing_page_code

### ISSUE THREAD

**Issue by eonist** [eonist/conduit#163]
Based on the image, I can create HTML and CSS code to replicate this Conduit design landing page:

## HTML Code

```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conduit - Design at the speed of thought</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <header>
            <div class="logo">
                <img src="logo.svg" alt="Conduit Logo">
            </div>
            <h1>Conduit</h1>
            <p class="tagline">Design at the speed of thought</p>
            <div class="github-badge">
                <span>134 stars on GitHub</span>
            </div>
        </header>

        <div class="features-grid">
            <!-- Feature 1 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <path d="M12 5l9 16H3l9-16z" stroke="currentColor" stroke-width="2"></path>
                    </svg>
                </div>
                <h2>Text manipulation</h2>
                <p>Enables AI-powered control to add, edit, and style text elements within your Figma designs.</p>
            </div>

            <!-- Feature 2 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <path d="M3 17h18M3 12h18M3 7h18" stroke="currentColor" stroke-width="2"></path>
                    </svg>
                </div>
                <h2>Gradient support</h2>
                <p>Allows the AI to create and apply vibrant gradient fills to various design elements.</p>
            </div>

            <!-- Feature 3 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <path d="M6 4h12M6 12h12M6 20h12" stroke="currentColor" stroke-width="2"></path>
                    </svg>
                </div>
                <h2>Font support</h2>
                <p>Provides the capability for the AI to access and apply a diverse range of fonts and typographic styles.</p>
            </div>

            <!-- Feature 4 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <rect x="3" y="3" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2"></rect>
                    </svg>
                </div>
                <h2>AutoLayout</h2>
                <p>Facilitates the automatic creation of responsive and adaptive layouts by leveraging Figma's AutoLayout feature.</p>
            </div>

            <!-- Feature 5 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <rect x="3" y="3" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2"></rect>
                    </svg>
                </div>
                <h2>Batch operations</h2>
                <p>Allows the AI to perform actions on multiple Figma elements simultaneously, enhancing workflow efficiency.</p>
            </div>

            <!-- Feature 6 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2"></circle>
                    </svg>
                </div>
                <h2>Geometric shapes</h2>
                <p>Enables the AI to generate common geometric shapes like rectangles, circles, and polygons as needed.</p>
            </div>

            <!-- Feature 7 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <path d="M4 4h16v16H4z" stroke="currentColor" stroke-width="2"></path>
                    </svg>
                </div>
                <h2>SVG / Image support</h2>
                <p>Supports the import and management of Scalable Vector Graphics (SVG) and raster images within Figma designs.</p>
            </div>

            <!-- Feature 8 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <rect x="3" y="3" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2"></rect>
                    </svg>
                </div>
                <h2>Frame, Group, Component</h2>
                <p>Allows the AI to structure designs effectively through the creation and management of frames, groups, and reusable components.</p>
            </div>

            <!-- Feature 9 -->
            <div class="feature-card">
                <div class="icon">
                    <svg viewBox="0 0 24 24" fill="none">
                        <path d="M12 5l9 16H3l9-16z" stroke="currentColor" stroke-width="2"></path>
                    </svg>
                </div>
                <h2>Rename layers</h2>
                <p>Provides the ability for the AI to programmatically rename layers, aiding in the organization of Figma files.</p>
            </div>
        </div>

        <div class="installation">
            <ol>
                <li>Clone the repo on GitHub</li>
                <li>Add MCP config to your agent</li>
                <li>Install plugin in Figma</li>
            </ol>
        </div>

        <button class="download-btn">Download</button>
    </div>
</body>
</html>

```

## CSS Code

```css
/* Reset and base styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
    background-color: #000;
    color: #fff;
    line-height: 1.5;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}

.container {
    max-width: 1100px;
    margin: 0 auto;
    padding: 50px 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
}

/* Header section */
header {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 50px;
    text-align: center;
}

.logo {
    width: 80px;
    height: 80px;
    background-color: #f0f0f0;
    border-radius: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 15px;
}

h1 {
    font-size: 28px;
    font-weight: 600;
    margin-bottom: 8px;
}

.tagline {
    color: #a0a0a0;
    font-size: 16px;
    margin-bottom: 20px;
}

.github-badge {
    background-color: rgba(255, 255, 255, 0.1);
    border-radius: 20px;
    padding: 8px 16px;
    font-size: 14px;
}

/* Features grid */
.features-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
    width: 100%;
    margin-bottom: 50px;
}

.feature-card {
    background-color: rgba(255, 255, 255, 0.05);
    border-radius: 16px;
    padding: 24px;
    display: flex;
    flex-direction: column;
    gap: 12px;
}

.icon {
    width: 40px;
    height: 40px;
    background-color: rgba(255, 255, 255, 0.08);
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 8px;
}

.icon svg {
    width: 24px;
    height: 24px;
    color: #fff;
}

.feature-card h2 {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 4px;
}

.feature-card p {
    font-size: 14px;
    color: #a0a0a0;
    line-height: 1.5;
}

/* Installation steps */
.installation {
    margin-bottom: 30px;
    text-align: center;
}

.installation ol {
    list-style-position: inside;
    display: flex;
    flex-direction: column;
    gap: 8px;
    color: #a0a0a0;
    font-size: 15px;
}

/* Download button */
.download-btn {
    background-color: white;
    color: black;
    border: none;
    border-radius: 20px;
    padding: 10px 25px;
    font-size: 16px;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.2s;
}

.download-btn:hover {
    background-color: #f0f0f0;
}

/* Responsive design */
@media (max-width: 900px) {
    .features-grid {
        grid-template-columns: repeat(2, 1fr);
    }
}

@media (max-width: 600px) {
    .features-grid {
        grid-template-columns: 1fr;
    }
}
```

## Additional Notes

For a complete implementation:

1. You'll need to create the Conduit logo (the blue gradient "C" in a white rounded square) as an SVG or use a custom font with gradient styling.

2. The icons shown in the example are simplified - in a real implementation, you'd want to create more detailed SVG icons that match the originals.

3. For the exact color scheme, you might need to adjust the CSS variables to match the exact gradient used in the Conduit logo (appears to be a blue-purple gradient).

4. The font used in the image appears to be a system font like Inter or SF Pro, so the font stack provided should be adequate.

This implementation creates a responsive design that will work well on desktop and mobile devices, matching the dark theme and card-based layout of the original design.

Citations:
[1] https://pplx-res.cloudinary.com/image/private/user_uploads/60313916/a6d7f52a-b250-48b3-b524-9d61c1735303/Landing-Page__Shadcn.jpg

---
Answer from Perplexity: [pplx.ai/share](https://www.perplexity.ai/search/pplx.ai/share)
